Repository AY2425S1-CS2113-T10-1/tp, pull requests merged in 2024-10, with the labels that each got.

#32 Implemented Ui class
  src/main/java/seedu/duke/Ui.java
Labels: type.Task

#31 Implemented Update Status
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/SortCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/exceptions/InvalidStatus.java
  src/test/java/seedu/duke/InternshipListTest.java
  src/test/java/seedu/duke/InternshipTest.java
Labels: type.Task, type.Bug

#33 Implement basic filter command functionality
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/FilterCommand.java
  src/main/java/seedu/commands/InternshipFieldGetter.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
Labels: type.Epic, type.Bug

#35 Create parser to understand user inputs
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/FilterCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/SortCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/EasInternship.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/duke/Parser.java
  src/test/Example Test Run
Labels: type.Task

#37 UpdateCommand update different fields
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
  src/test/java/seedu/commands/UpdateCommandTest.java
Labels: type.Task, priority.Medium, severity.Medium

#36 Create Storage Class
  src/main/java/seedu/duke/EasInternship.java
  src/main/java/seedu/duke/Storage.java
Labels: type.Story

#45 Branch update exceptions
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/exceptions/InvalidIndex.java
  src/main/java/seedu/ui/UiCommand.java
  src/test/java/seedu/commands/UpdateCommandTest.java
  src/test/java/seedu/duke/InternshipListTest.java
  src/test/java/seedu/duke/InternshipTest.java
Labels: type.Task, priority.Medium, severity.Medium

#53 Fix update command exception output
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/InternshipList.java
Labels: type.Bug, priority.Medium, severity.Medium

#57 made error handling for add command more comprehensive
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/ui/UiCommand.java
Labels: type.Bug, priority.Medium

#73 Edit update function output
  src/main/java/seedu/ui/UiCommand.java
Labels: type.Bug, priority.Medium, severity.Low

#74 Add function to add and remove specific skills
  data/EasInternship.txt
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/exceptions/MissingValue.java
  src/main/java/seedu/ui/UiCommand.java
  src/test/java/seedu/commands/RemoveCommandTest.java
  src/test/java/seedu/commands/UpdateCommandTest.java
  src/test/java/seedu/duke/InternshipListTest.java
  src/test/java/seedu/duke/InternshipTest.java
Labels: type.Task, priority.Medium, severity.Medium

#78 Remove data file from repository and add to .gitignore
  .gitignore
  data/EasInternship.txt
Labels: type.Bug, priority.Medium

#69 Enable assertions and extend filter command functionality
  .gitignore
  build.gradle
  src/main/java/seedu/commands/FilterCommand.java
  src/main/java/seedu/commands/SortCommand.java
  src/main/java/seedu/duke/EasInternship.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/commands/FilterCommandTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: type.Enhancement, priority.High

#76 Able to update deadlines
  .gitignore
  data/EasInternship.txt
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/exceptions/InvalidDeadline.java
  src/main/java/seedu/ui/UiCommand.java
  src/test/java/seedu/commands/UpdateCommandTest.java
  src/test/java/seedu/duke/InternshipListTest.java
  src/test/java/seedu/duke/InternshipTest.java
Labels: type.Task, priority.High, severity.Medium

#83 Add UpdateCommand to Developer Guide
  docs/DeveloperGuide.md
  docs/UML/UpdateCommand.puml
  docs/UML/UpdateCommand_Sequence_Diagram.png
  src/main/java/seedu/commands/UpdateCommand.java
Labels: type.Enhancement, priority.High, severity.Medium
