Repository AY2425S1-CS2113-T10-1/tp, pull requests merged in 2024-11, with the labels that each got.

#87 Add RemoveCommand to developer guide
  docs/DeveloperGuide.md
  docs/UML/RemoveCommand.puml
  docs/UML/RemoveCommand_Sequence_Diagram.png
Labels: type.Task, priority.Medium, severity.Medium

#96 Draft PPP (Ting Hui)
  docs/team/tantinghui.md
Labels: type.Enhancement, priority.Low, severity.Low, Documentation

#86 Able to remove deadlines as well
  data/EasInternship.txt
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
  src/test/java/seedu/commands/RemoveCommandTest.java
  src/test/java/seedu/duke/InternshipListTest.java
  src/test/java/seedu/duke/InternshipTest.java
Labels: type.Task, priority.Medium, severity.Medium

#98 Add Calendar Function
  data/EasInternship.txt
  src/main/java/seedu/commands/CalendarCommand.java
  src/main/java/seedu/duke/Deadline.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/ui/UiCommand.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#113 Refactor output of SortCommand
  src/main/java/seedu/commands/SortCommand.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/ui/UiCommand.java
  src/main/java/seedu/ui/UiInternshipList.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#112 Add CalendarCommand getUsage to HelpCommand
  src/main/java/seedu/commands/HelpCommand.java
Labels: type.Task, priority.Medium, severity.VeryLow

#105 Update User Guide
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.Medium, Documentation

#128 Add Logging to Methods and Classes
  build.gradle
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/EasInternship.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.Medium, severity.Medium

#132 Continue Adding Logging
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/CalendarCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/FavouriteCommand.java
  src/main/java/seedu/commands/FilterCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/SortCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/duke/Parser.java
Labels: type.Task, priority.Medium, severity.Medium

#137 Add commands to UG and fix FavouriteCommand bug
  docs/UserGuide.md
  src/main/java/seedu/commands/FavouriteCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/duke/InternshipList.java
Labels: type.Story, type.Bug, Documentation

#140 Handle invalid date inputs for AddCommand
  src/main/java/seedu/commands/AddCommand.java
Labels: type.Bug, priority.High, severity.Medium

#139 Add PPP version 1.0
  docs/team/rahul.md
Labels: Documentation

#215 [Please Merge :)] Clear bugs from update function
  docs/UserGuide.md
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/CalendarCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/DeleteCommand.java
  src/main/java/seedu/commands/FavouriteCommand.java
  src/main/java/seedu/commands/FilterCommand.java
  src/main/java/seedu/commands/HelpCommand.java
  src/main/java/seedu/commands/ListCommand.java
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/commands/SortCommand.java
  src/main/java/seedu/commands/UpdateCommand.java
  src/main/java/seedu/duke/Deadline.java
  src/main/java/seedu/duke/Internship.java
  src/main/java/seedu/duke/InternshipList.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
Labels: type.Task, severity.Medium

#223 Improve Calendar Function
  docs/UserGuide.md
  src/main/java/seedu/commands/CalendarCommand.java
  src/main/java/seedu/ui/UiCommand.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#224 Edit Developer Guide
  docs/DeveloperGuide.md
  docs/UML/CalendarCommand.puml
  docs/UML/CalendarCommand_Sequence_Diagram.png
  docs/UML/RemoveCommand.puml
  docs/UML/RemoveCommand_Sequence_Diagram.png
  docs/UML/Ui Component.puml
  docs/UML/Ui_Component.png
  docs/UML/UpdateCommand.puml
  docs/UML/UpdateCommand_Sequence_Diagram.png
  src/main/java/seedu/ui/UiCommand.java
Labels: type.Bug, priority.High, severity.Medium, Documentation, DG

#231 Edit message to Remove deadline
  README.md
  build.gradle
  src/main/java/seedu/commands/AddCommand.java
  src/main/java/seedu/commands/CalendarCommand.java
  src/main/java/seedu/commands/Command.java
  src/main/java/seedu/commands/FavouriteCommand.java
  src/main/java/seedu/commands/FilterCommand.java
  src/main/java/seedu/commands/InternshipFieldGetter.java
  src/main/java/seedu/commands/RemoveCommand.java
  src/main/java/seedu/easinternship/Deadline.java
  src/main/java/seedu/easinternship/EasInternship.java
  src/main/java/seedu/easinternship/Internship.java
  src/main/java/seedu/easinternship/InternshipList.java
  src/main/java/seedu/easinternship/Parser.java
  src/main/java/seedu/easinternship/Storage.java
  src/main/java/seedu/ui/UiCommand.java
  src/main/java/seedu/ui/UiInternshipList.java
  src/test/java/seedu/commands/AddCommandTest.java
  src/test/java/seedu/commands/FavouriteCommandTest.java
  src/test/java/seedu/commands/FilterCommandTest.java
  src/test/java/seedu/commands/RemoveCommandTest.java
  src/test/java/seedu/commands/SortCommandTest.java
  src/test/java/seedu/commands/UpdateCommandTest.java
  src/test/java/seedu/easinternship/DukeTest.java
  src/test/java/seedu/easinternship/InternshipListTest.java
  src/test/java/seedu/easinternship/InternshipTest.java
  src/test/java/seedu/easinternship/ParserTest.java
Labels: type.Enhancement, priority.Medium, severity.Low

#235 Update PPP
  docs/README.md
  docs/team/jadenlimjc.md
  docs/team/ridiculouswifi.md
  docs/team/toby-yu.md
Labels: type.Task, priority.High, severity.Low

#237 Fix minor typos to ridiculouswifi PPP
  docs/README.md
  docs/team/ridiculouswifi.md
Labels: type.Bug, Documentation

#241 Rahul PPP v2.0
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/rahul.md
Labels: Documentation

#245 Update UG
  META-INF/MANIFEST.MF
  build.gradle
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#247 Fix errors in DG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, severity.Medium, Documentation, DG

#248 Fix sort by deadline
  src/main/java/seedu/easinternship/InternshipList.java
Labels: type.Bug, priority.High, severity.High
